# Generated by Django 4.2.2 on 2025-12-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_users_list", "Может просматривать список пользователей"),
                    ("can_block_users", "Может блокировать пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(
                default=False, help_text="Пользователь заблокирован?"
            ),
        ),
    ]
