# Generated by Django 4.2.2 on 2025-12-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_user_is_blocked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_users_list", "Может просматривать список пользователей"),
                    ("can_block_users", "Может блокировать пользователей"),
                    ("can_unblock_users", "Может разблокировать пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
