# Generated by Django 5.2.8 on 2025-11-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=250, verbose_name="Тема письма"),
                ),
                ("message", models.TextField(verbose_name="Письмо")),
            ],
            options={
                "verbose_name": "Cooбщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["subject"],
            },
        ),
    ]
