# Generated by Django 5.2.8 on 2025-12-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0003_mailing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="completed_at",
            new_name="end_time",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="launched_at",
        ),
        migrations.AddField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время начала отправки"
            ),
        ),
    ]
