# Generated by Django 5.2.8 on 2025-12-06 06:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0004_rename_completed_at_mailing_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 5, 5, 59, 13, 949312, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время окончания отправки",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 8, 6, 1, 9, 639740, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время начала отправки",
            ),
            preserve_default=False,
        ),
    ]
