# Generated by Django 5.2.8 on 2025-12-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0006_attemptsendmailing"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptsendmailing",
            name="recipient",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing_service.mailingrecipient",
                verbose_name="Получатель",
            ),
            preserve_default=False,
        ),
    ]
