# Generated by Django 5.2.8 on 2025-12-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0007_attemptsendmailing_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="Статус отправки"),
        ),
    ]
