# Generated by Django 5.2.8 on 2025-12-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0008_mailing_is_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="is_sent",
        ),
    ]
