# Generated by Django 4.2.2 on 2025-12-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0010_mailing_owner_mailingmessage_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_disable_mailing", "Может отключать рассылки"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingmessage",
            options={
                "ordering": ["subject"],
                "permissions": [
                    ("can_view_all_messages", "Может просматривать все сообщения")
                ],
                "verbose_name": "Cooбщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_view_all_recipients", "Может просматривать всех клиентов")
                ],
                "verbose_name": "получатель рассылки",
                "verbose_name_plural": "получатели рассылки",
            },
        ),
    ]
